### ISSUE TITLE
Stock/Inventory Information not available in GraphQL

### ISSUE THREAD

**Issue by amandeepsinghvirdi** [bigcommerce/storefront-api-examples#1]
Was expecting Stock Level information under: 
Site > Product > Variants 

But there is no endpoint for fetching the stock level of a variant/sku.

**Comment by bookernath** [comment]
Hi @amandeepsinghvirdi,

This is planned for a future release of the API. I'll make a note to comment on this issue when we're closer to a release.

**Comment by deepak-aupchaarik** [comment]
> This is planned for a future release of the API. I'll make a note to comment on this issue when we're closer to a release.

Has there been any update on this since? It's been 3 years, the idea has been dropped?

**Comment by bookernath** [comment]
This has been available for some time now, for example:

```
query {
  site {
    products {
      edges {
        cursor
        node {
          entityId
          name
          inventory {
            aggregated {
              availableToSell
            }
          }
        }
      }
    }
  }
}```

**Comment by Tigatok** [comment]
@bookernath is there anything that has to be done to have that aggregated field populated? No matter the value on my storefront/admin ui, the value is null.

I find it odd that the Track Inventory button seems to be purely a UI conditional field. If you uncheck Track Inventory, but you had stock previously, it provides "true". If you did not have stock, and uncheck the field, it provides "false".

TIA
