### ISSUE TITLE
Only "Price" filter returned for graphQL query for all filters of a given category

### ISSUE THREAD

**Issue by cale-sweeney** [bigcommerce/storefront-api-examples#4]
With the following graphQL query, I was expecting to get a list of faceted filters for a given category.  In this case, category id "764", but this is true for all the categories that we experimented with.

```
query getFilters($filters: SearchProductsFiltersInput!){
            site{
              search{
                searchProducts(filters: $filters){
                  filters{

                    edges{
                      node{
                        name
                        
                      }
                    }
                  }
                }
              }
            }
          }

{"filters": {"categoryEntityId": 764}}
```

Unfortunately it only seems to be returning the price filter.  In the store configuration, we definitely have more than just Price checked off for product filtering.  Are we doing something wrong in the query above, or is this a known bug/issue?

![Selected Product Filters](https://user-images.githubusercontent.com/4062624/175094604-7d5cc1fe-103b-4a41-a6f3-69351001e479.PNG)

**Comment by bookernath** [comment]
Hi, please raise an issue with our support team about this one. This repo is not actively monitored.
